name       : libxcrypt
version    : 4.4.30
release    : 1
source     :
    - https://github.com/besser82/libxcrypt/releases/download/v4.4.30/libxcrypt-4.4.30.tar.xz : b3667f0ba85daad6af246ba4090fbe53163ad93c8b6a2a1257d22a78bb7ceeba
license    : LGPL-2.1-or-later
component  : system.base
summary    : Extended crypt library for descrypt, md5crypt, bcrypt, and others
description: |
    libxcrypt is a modern library for one-way hashing of passwords. It supports a wide variety of both modern and historical hashing methods: yescrypt, gost-yescrypt, scrypt, bcrypt, sha512crypt, sha256crypt, md5crypt, SunMD5, sha1crypt, NT, bsdicrypt, bigcrypt, and descrypt. It provides the traditional Unix interfaces as well as a set of extended interfaces pioneered by Openwall Linux.
emul32     : yes
setup      : |
    %configure \
      --disable-static \
      --enable-hashes=strong,glibc \
      --enable-obsolete-api=no \
      --disable-failure-tokens
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
