name       : libxcrypt
version    : 4.4.33
release    : 3
source     :
    - https://github.com/besser82/libxcrypt/releases/download/v4.4.33/libxcrypt-4.4.33.tar.xz : e87acf9c652c573a4713d5582159f98f305d56ed5f754ce64f57d4194d6b3a6f
license    : LGPL-2.1-or-later
component  : system.base
summary    : Extended crypt library for descrypt, md5crypt, bcrypt, and others
description: |
    libxcrypt is a modern library for one-way hashing of passwords. It supports a wide variety of both modern and historical hashing methods: yescrypt, gost-yescrypt, scrypt, bcrypt, sha512crypt, sha256crypt, md5crypt, SunMD5, sha1crypt, NT, bsdicrypt, bigcrypt, and descrypt. It provides the traditional Unix interfaces as well as a set of extended interfaces pioneered by Openwall Linux.
emul32     : yes
devel      : yes
mancompress: yes
setup      : |
    %configure \
      --disable-static \
      --enable-hashes=strong,glibc \
      --enable-obsolete-api=no \
      --disable-failure-tokens
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
